[package]
name = "paymentprocessor"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
indexmap = "2.11.4"
polars = { version = "0.51.0", features = ["lazy", "dtype-struct"] }
thiserror = "2.0.16"
