name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:

  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

      name: Test `cargo check/test/build` on ${{ matrix.os }}
      runs-on: ${{ matrix.os }}

      env:
        CARGO_TERM_COLOR: always

      steps:
        - uses: Swatinem/rust-cache@v2.8.1
          with:
            persist-credentials: false

        - run: rustup toolchain install stable --profile minimal --no-self-update

        - uses: ./
          with:
            workspaces: tests

        - run: |
            cargo check
            cargo test
            cargo build --release




